name: "Examine BASH_ENV"

on: [push, pull_request, workflow_dispatch]

jobs:
  examine-bash-env:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-24.04-arm
        - macos-latest
        - windows-latest
        - windows-11-arm
      fail-fast: false

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Check for BASH_ENV
      run: printenv BASH_ENV || echo 'not present'

    - name: Try setting BASH_ENV
      run: echo 'BASH_ENV=helpers.sh' >>"$GITHUB_ENV"

    - name: Try using BASH_ENV to source a helper
      run: |
        hello() { echo 'Hello, world!!'; }
        declare -f hello >>"$BASH_ENV"

    - name: Try calling the helper
      run: hello
