name: Test if PowerShell fails fast

on: [push, pull_request, workflow_dispatch]

jobs:
  show-node-version:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: External command reporting failure
        run: |
          echo a >t
          git add t
          echo b >>t
          git diff --exit-code -- t  # Should fail.
          git log --oneline -1  # Should succeed, if run.
      - name: Cmdlet reporting an error
        run: |
          cat foo
          echo done
