# This is a basic workflow to help you get started with Actions

name: CI

env:
  text: foo bar

on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Interpolation without quotes
      - name: Run a command with a variable, allowing expansion
        run: printf '%s\n' '%s\n' ${{ env.text }}  # Doubling '%s\n', to see it too.

      # Interpolation with double quotes
      - name: Run a command with a variable, suppressing expansion
        run: printf '%s\n' '%s\n' "${{ env.text }}"  # Doubling '%s\n', to see it too.
