name: "Matrix into env"

on: [push, pull_request]

jobs:
  laud:
    strategy:
      matrix:
        laureate: [Alice, Bob]

    runs-on: ubuntu-latest

    env:
      HONOREE: ${{ matrix.laureate }}

    steps:
    - name: Laud the laureate
      run: echo "Today we honor $HONOREE!"
