name: readthedocs/actions
on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
    - uses: readthedocs/actions/preview@v1
      with:
        project-slug: "fake-slug"  # Fake slug for testing.
        message-template: |
          ----
          📚 [Documentation preview]({docs-pr-index-url}) (see [all builds](https://readthedocs.org/projects/fake-slug/builds/)) 📚 
