name: Try to force Node 20

on:
  pull_request:
  # pull_request_target:
  #   types: [opened]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: "true"

jobs:
  show-node-version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/github-script@v6  # Normally uses Node 16.
      with:
        script: |
          console.log(`Node.js version: ${process.version}`);
